// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type FellowTravelers struct {
	ID              uuid.UUID     `json:"id"`
	TripID          uuid.UUID `json:"trip_id"`
	FellowFirstName string        `json:"fellow_first_name"`
	FellowLastName  string        `json:"fellow_last_name"`
	FellowEmail     string        `json:"fellow_email"`
}

type Trips struct {
	ID        uuid.UUID     `json:"id"`
	TripName  string        `json:"trip_name"`
	StartDate time.Time     `json:"start_date"`
	EndDate   time.Time     `json:"end_date"`
	UserID    uuid.UUID `json:"user_id"`
}

type Users struct {
	ID           uuid.UUID `json:"id"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}
